#!/bin/sh
if [ "$1" = "remove" ]; then
	rm -rf /usr/lib/enigma2/python/Plugins/SystemPlugins/PowerCockpit > /dev/null 2>&1
	echo "PowerCockpit plugin removed successfully."
else
	find /usr/lib/enigma2/python/Plugins/SystemPlugins/PowerCockpit -type f -name "*.pyo" -exec rm -f {} \; > /dev/null 2>&1
fi
exit 0
